name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true
  CHANGESET: "true"

permissions:
  contents: write
  issues: write

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          # This is important for the changesets action to work properly
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      # Configure Git to ignore hooks when the action is running
      - name: Configure Git for Changesets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Skip Husky hooks for Changesets commits
          git config --global core.hooksPath /dev/null
      
      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
