name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true
  HUSKY: 0

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      - name: Disable Git hooks
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Method 1: Replace hooks directory with empty one
          mkdir -p /tmp/empty-hooks
          git config --global core.hooksPath /tmp/empty-hooks
          
          # Method 2: Create a .huskyrc that disables husky
          echo 'HUSKY=0' > .huskyrc
          
          # Method 3: Rename .husky directory temporarily
          if [ -d ".husky" ]; then
            mv .husky .husky.bak
          fi
      
      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
      
      - name: Cleanup
        if: always()
        run: |
          if [ -d ".husky.bak" ]; then
            mv .husky.bak .husky
          fi